stages:
  - build

build_outputs:
   stage: build
   image: debian:10
   script:
     - echo 'deb http://deb.debian.org/debian buster-backports main' > /etc/apt/sources.list.d/backports.list
     - apt-get update
     - apt-get update --fix-missing
     - apt-get -y install git libgtk-3-dev libcairo2-dev libgit2-dev transfig imagemagick gerbv python3 python3-pip software-properties-common expect-dev

     - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@dev.antmicro.com/git/antmicro-kmake-script.git
     - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@dev.antmicro.com/git/antmicro-kicad-components.git
     #antmicro-kicad-components/update_global_libs.sh antmicro-kicad-components/kicad_libraries kmake/kicad-automation-scripts/config /root/antmicro-kicad-components/kicad_libraries
     - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@dev.antmicro.com/git/antmicro-picknplace-job-maker.git
     - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@dev.antmicro.com/git/kicad-blender-exporter.git
     - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@dev.antmicro.com/git/antmicro-blender-models.git
     - ls
     - cp antmicro-kmake-script/kmake/kmake.py /usr/bin/kmake
     - cp antmicro-kmake-script/kmake/km_parsers.py /usr/bin/
     - cp antmicro-kmake-script/kmake/km_pcbapi.py /usr/bin/

     - cp -r antmicro-kmake-script/kmake/kicad-automation-scripts/src/eeschema/ /usr/local/lib/python3.7/dist-packages/eeschema
     - cp -r antmicro-kmake-script/kmake/kicad-automation-scripts/src/pcbnew_automation/ /usr/local/lib/python3.7/dist-packages/pcbnew_automation
     - cp -r antmicro-kmake-script/kmake/kicad-automation-scripts/src/util/ /usr/local/lib/python3.7/dist-packages/util

     - apt-get update
     - apt-get install -f -y xvfb recordmydesktop xdotool xclip wget

     - apt-get remove -y kicad
     - apt-get install -y kicad="5.1.9+dfsg1-1~bpo10+1"

#ENV LANG C.UTF-8

     - pip3 install xvfbwrapper==0.2.9 argparse==1.2.1 PyPDF2==1.26.0 junit-xml==1.8
     - pip3 install psutil
     - wget https://gmsh.info/bin/Linux/gmsh-4.5.6-Linux64.tgz
     - tar -xvzf gmsh-4.5.6-Linux64.tgz -C /usr/ --strip 1
     - rm gmsh-4.5.6-Linux64.tgz

     - mkdir -p ~/.config/kicad/
     - cp -r antmicro-kmake-script/kmake/kicad-automation-scripts/config/. ~/.config/kicad/

     - cp antmicro-picknplace-job-maker/jmake.py /usr/bin/jmake
     - cp antmicro-picknplace-job-maker/default-stacktable.csv /usr/bin/default-stacktable.csv

     - wget https://ftp.nluug.nl/pub/graphics/blender/release/Blender2.93/blender-2.93.0-linux-x64.tar.xz
     - tar -xvf blender-2.93.0-linux-x64.tar.xz
     - rm blender-2.93.0-linux-x64.tar.xz
     - blender-2.93.0-stable+blender-v293-release.84da05a8b806-linux.x86_64-release/2.93/python/bin/python3.9 -m ensurepip
     - blender-2.93.0-stable+blender-v293-release.84da05a8b806-linux.x86_64-release/2.93/python/bin/python3.9 -m pip install --upgrade pip
     - blender-2.93.0-stable+blender-v293-release.84da05a8b806-linux.x86_64-release/2.93/python/bin/python3.9 -m pip install xvfbwrapper
     - echo -e '#!/bin/bash\nblender-2.93.0-stable+blender-v293-release.84da05a8b806-linux.x86_64-release/blender "$@"' > /usr/bin/blender293
     - chmod +x /usr/bin/blender293

     - cp kicad-blender-exporter/gerbv_png.sh /usr/bin/gerbv_png
     - cp kicad-blender-exporter/gerbv_convert.sh /usr/bin/gerbv_convert
     - cp kicad-blender-exporter/generate_ci.sh /usr/bin/generate

     - kmake sch debug || echo PDF schematic error
     - kmake dnp
     - kmake bom
     - kmake assemblydrw
     - kmake pastedrw
     - kmake gerber noedge
#     - kmake fixoutline
#     - kmake 3d || echo 3d viz error
     - kmake step || echo STEP output error
#     - R="antmicro-picknplace-job-maker"; git clone -n --depth 1 https://gitlab-ci-token:${CI_JOB_TOKEN}@dev.antmicro.com/git/$R.git && git -C $R show HEAD:default-stacktable.csv > stacktable.csv && rm -rf $R
     - kmake pnp
     - kmake drc debug || echo PDF schematic error
#     - kmake sourcing > doc/sourcing.rpt
#     - kmake 3d ray || echo 3d viz raytracing error
     - generate fab/ 1200

   artifacts:
     expire_in: 2 week
     paths:
       - doc/*.pdf
       - doc/*.csv
       - doc/*.rpt
       - fab/*.gbr
       - fab/*.drl
       - fab/*.pdf
       - fab/*.csv
       - fab/*.dpv
       - img/*.png
       - 3d-model/*.stp
       - fab/*.blend
       - fab/wireframe*
       - fab/renders/*
#STLopt       - 3d-model/*.stl
#       - img/*.ogv
#       - doc/*.ogv
#   when: manual
